
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL.ChildDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class NamunaMaster
{

    public int NamunaId { get; set; }

    public string RMNAME { get; set; }

    public string PropertyNo { get; set; }

    public string PropertyDescription { get; set; }

    public string OwnerName { get; set; }

    public string OccupantName { get; set; }

    public string Used { get; set; }

    public string AVRent { get; set; }

    public string BDBVRent { get; set; }

    public string BNDBVRent { get; set; }

    public string EKJYRent { get; set; }

    public string DEPercentV { get; set; }

    public string EKJKYPrice { get; set; }

    public string EMTax { get; set; }

    public string TreeTax { get; set; }

    public string EducationTax { get; set; }

    public string RSubTax { get; set; }

    public string OtherTax { get; set; }

    public string TotalTax { get; set; }

    public string TaxBuldingLand { get; set; }

    public string TaxA { get; set; }

    public string TaxB { get; set; }

    public string TaxC { get; set; }

    public string TaxD { get; set; }

    public string TaxABCD { get; set; }

    public string Signatures { get; set; }

    public string Stamp { get; set; }

    public string NTK { get; set; }

    public string NWord { get; set; }

    public string LF { get; set; }

    public string TF { get; set; }

    public string RP2 { get; set; }

    public string RP { get; set; }

    public string SurvivorName { get; set; }

    public string DataEntryName { get; set; }

    public Nullable<System.DateTime> SurvivorDate { get; set; }

    public Nullable<System.DateTime> DataEntryDate { get; set; }

    public string RMNAME2 { get; set; }

    public string PropertyNo2 { get; set; }

    public string PropertyDescription2 { get; set; }

    public string OwnerName2 { get; set; }

    public string OccupantName2 { get; set; }

    public string Used2 { get; set; }

    public string AVRent2 { get; set; }

    public string BDBVRent2 { get; set; }

    public string BNDBVRent2 { get; set; }

    public string EKJYRent2 { get; set; }

    public string DEPercentV2 { get; set; }

    public string EKJKYPrice2 { get; set; }

    public string EMTax2 { get; set; }

    public string TreeTax2 { get; set; }

    public string EducationTax2 { get; set; }

    public string RSubTax2 { get; set; }

    public string OtherTax2 { get; set; }

    public string TotalTax2 { get; set; }

    public string TaxBuldingLand2 { get; set; }

    public string TaxA2 { get; set; }

    public string TaxB2 { get; set; }

    public string TaxC2 { get; set; }

    public string TaxD2 { get; set; }

    public string TaxABCD2 { get; set; }

    public string Signatures2 { get; set; }

    public string Stamp2 { get; set; }

    public string AppilcantName { get; set; }

    public Nullable<System.DateTime> ApplicantDate { get; set; }

    public string TaxRegister { get; set; }

    public Nullable<System.DateTime> TaxRegisterDate { get; set; }

    public string RMNAME3 { get; set; }

    public string PropertyNo3 { get; set; }

    public string PropertyDescription3 { get; set; }

    public string OwnerName3 { get; set; }

    public string OccupantName3 { get; set; }

    public string Used3 { get; set; }

    public string AVRent3 { get; set; }

    public string BDBVRent3 { get; set; }

    public string BNDBVRent3 { get; set; }

    public string EKJYRent3 { get; set; }

    public string DEPercentV3 { get; set; }

    public string EKJKYPrice3 { get; set; }

    public string EMTax3 { get; set; }

    public string TreeTax3 { get; set; }

    public string EducationTax3 { get; set; }

    public string RSubTax3 { get; set; }

    public string OtherTax3 { get; set; }

    public string TotalTax3 { get; set; }

    public string TaxBuldingLand3 { get; set; }

    public string TaxA3 { get; set; }

    public string TaxB3 { get; set; }

    public string TaxC3 { get; set; }

    public string TaxD3 { get; set; }

    public string TaxABCD3 { get; set; }

    public string Signatures3 { get; set; }

    public string Stamp3 { get; set; }

    public string RMNAME4 { get; set; }

    public string PropertyNo4 { get; set; }

    public string PropertyDescription4 { get; set; }

    public string OwnerName4 { get; set; }

    public string OccupantName4 { get; set; }

    public string Used4 { get; set; }

    public string AVRent4 { get; set; }

    public string BDBVRent4 { get; set; }

    public string BNDBVRent4 { get; set; }

    public string EKJYRent4 { get; set; }

    public string DEPercentV4 { get; set; }

    public string EKJKYPrice4 { get; set; }

    public string EMTax4 { get; set; }

    public string TreeTax4 { get; set; }

    public string EducationTax4 { get; set; }

    public string RSubTax4 { get; set; }

    public string OtherTax4 { get; set; }

    public string TotalTax4 { get; set; }

    public string TaxBuldingLand4 { get; set; }

    public string TaxA4 { get; set; }

    public string TaxB4 { get; set; }

    public string TaxC4 { get; set; }

    public string TaxD4 { get; set; }

    public string TaxABCD4 { get; set; }

    public string Signatures4 { get; set; }

    public string Stamp4 { get; set; }

    public string RMNAME5 { get; set; }

    public string PropertyNo5 { get; set; }

    public string PropertyDescription5 { get; set; }

    public string OwnerName5 { get; set; }

    public string OccupantName5 { get; set; }

    public string Used5 { get; set; }

    public string AVRent5 { get; set; }

    public string BDBVRent5 { get; set; }

    public string BNDBVRent5 { get; set; }

    public string EKJYRent5 { get; set; }

    public string DEPercentV5 { get; set; }

    public string EKJKYPrice5 { get; set; }

    public string EMTax5 { get; set; }

    public string TreeTax5 { get; set; }

    public string EducationTax5 { get; set; }

    public string RSubTax5 { get; set; }

    public string OtherTax5 { get; set; }

    public string TotalTax5 { get; set; }

    public string TaxBuldingLand5 { get; set; }

    public string TaxA5 { get; set; }

    public string TaxB5 { get; set; }

    public string TaxC5 { get; set; }

    public string TaxD5 { get; set; }

    public string TaxABCD5 { get; set; }

    public string Signatures5 { get; set; }

    public string Stamp5 { get; set; }

    public string LFee { get; set; }

    public Nullable<bool> IsDelete { get; set; }

}

}
